name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.4.1)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
    
    - name: Build package
      run: |
        pip install build
        python -m build
    
    - name: Check package
      run: |
        pip install twine
        twine check dist/*
    
    - name: Generate changelog
      id: changelog
      run: |
        if [ -f CHANGELOG.md ]; then
          # Extract the changelog for this version
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "## Changes in v$VERSION" > release_notes.md
          echo "" >> release_notes.md
          echo "### Features" >> release_notes.md
          echo "- Physics-Informed Fractional Operator Learning for Real-Time Neurological Biomarker Detection" >> release_notes.md
          echo "- Memory-Driven EEG Analysis Framework" >> release_notes.md
          echo "- Advanced benchmarking and validation system" >> release_notes.md
          echo "- Multiple estimation methods (temporal, spectral, wavelet, multifractal)" >> release_notes.md
          echo "- Biomedical scenarios and neurological condition support" >> release_notes.md
          echo "- GPU acceleration with JAX and NumPyro integration" >> release_notes.md
          echo "" >> release_notes.md
          echo "### Research Context" >> release_notes.md
          echo "Developed as part of PhD research in Biomedical Engineering at the University of Reading, UK by Davian R. Chin." >> release_notes.md
        else
          echo "No changelog found" > release_notes.md
        fi
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        files: |
          dist/*